{% set name = "pgeocode" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pgeocode-{{ version }}.tar.gz
  sha256: 60fc2bad60aa161c3cf46ace4fde607b77e016b1e2a25470534163305499e55e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pandas
    - python >=3.6
    - requests

test:
  imports:
    - pgeocode
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pgeocode/
  summary: Approximate geocoding
  license: BSD-1-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
